version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    # 本番は静的ファイルをnginx等で配信するのが一般的
    # ここではDockerfileでビルドし、nginxで配信する場合の例
    # nginx用のDockerfileが必要

  backend:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile # ←発行用Dockerfileを作成推奨
    ports:
      - "5000:5000"
    env_file:
      - ./JobHuntX.API/.env
    environment:
      - ASPNETCORE_URLS=http://+:5000
