version: '3.8'
services:
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./client-app:/app
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "build"]

  backend:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    working_dir: /app
    volumes:
      - ./JobHuntX:/app
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
