# Stage 1: Build React frontend
FROM node:18 AS frontend-dev
WORKDIR /app
COPY ./client-app/package*.json ./client-app/
RUN cd ./client-app && npm install
COPY ./client-app ./client-app
CMD ["npm", "start"]

# Stage 2: ASP.NET Core backend
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS backend-dev
WORKDIR /src
COPY ./JobHuntX/JobHuntX.csproj ./JobHuntX/
RUN dotnet restore ./JobHuntX/JobHuntX.csproj
COPY . .
ENV ASPNETCORE_URLS=http://+:5000
EXPOSE 5000
CMD ["dotnet", "watch", "run", "--project", "JobHuntX/JobHuntX.csproj"]
