version: '3.8'
services:
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./client-app:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true  # WSLでホットリロードを有効にする
    command: ["npm", "start"]  # npm install は明示的に実行するほうが良い

  backend:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    working_dir: /src
    volumes:
      - .:/src
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000 # dotnet watch 環境ではProgram.cs実行タイミングでこの環境変数を読み取れない
      - DOTNET_USE_POLLING_FILE_WATCHER=1  # WSLで変更検知を有効化
    command: ["dotnet", "watch", "run", "--project", "JobHuntX.API/JobHuntX.API.csproj"]
