//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export class Client {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @param key (optional) 
     * @return OK
     */
    jobs(key: string | undefined): Promise<JobListResponse> {
        let url_ = this.baseUrl + "/api/jobs?";
        if (key === null)
            throw new Error("The parameter 'key' cannot be null.");
        else if (key !== undefined)
            url_ += "key=" + encodeURIComponent("" + key) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processJobs(_response);
        });
    }

    protected processJobs(response: Response): Promise<JobListResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = JobListResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<JobListResponse>(null as any);
    }

    /**
     * @param key (optional) 
     * @return OK
     */
    remoteok(key: string | undefined): Promise<JobListResponse> {
        let url_ = this.baseUrl + "/api/remoteok?";
        if (key === null)
            throw new Error("The parameter 'key' cannot be null.");
        else if (key !== undefined)
            url_ += "key=" + encodeURIComponent("" + key) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRemoteok(_response);
        });
    }

    protected processRemoteok(response: Response): Promise<JobListResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = JobListResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<JobListResponse>(null as any);
    }

    /**
     * @param key (optional) 
     * @return OK
     */
    weworkrss(key: string | undefined): Promise<JobListResponse> {
        let url_ = this.baseUrl + "/api/weworkrss?";
        if (key === null)
            throw new Error("The parameter 'key' cannot be null.");
        else if (key !== undefined)
            url_ += "key=" + encodeURIComponent("" + key) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processWeworkrss(_response);
        });
    }

    protected processWeworkrss(response: Response): Promise<JobListResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = JobListResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<JobListResponse>(null as any);
    }

    /**
     * @return OK
     */
    sample(): Promise<JobListResponse> {
        let url_ = this.baseUrl + "/api/sample";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSample(_response);
        });
    }

    protected processSample(response: Response): Promise<JobListResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = JobListResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<JobListResponse>(null as any);
    }

    /**
     * @return OK
     */
    keywords(): Promise<KeywordTags> {
        let url_ = this.baseUrl + "/api/keywords";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processKeywords(_response);
        });
    }

    protected processKeywords(response: Response): Promise<KeywordTags> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = KeywordTags.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<KeywordTags>(null as any);
    }

    /**
     * @return OK
     */
    status(): Promise<string> {
        let url_ = this.baseUrl + "/api/status";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processStatus(_response);
        });
    }

    protected processStatus(response: Response): Promise<string> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : <any>null;
    
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<string>(null as any);
    }

    /**
     * @return OK
     */
    candidates(): Promise<Candidate[]> {
        let url_ = this.baseUrl + "/api/candidates";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCandidates(_response);
        });
    }

    protected processCandidates(response: Response): Promise<Candidate[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(Candidate.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Candidate[]>(null as any);
    }
}

export class ApiMessage implements IApiMessage {
    type?: ApiMessageType;
    text?: string | undefined;

    constructor(data?: IApiMessage) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.type = _data["type"];
            this.text = _data["text"];
        }
    }

    static fromJS(data: any): ApiMessage {
        data = typeof data === 'object' ? data : {};
        let result = new ApiMessage();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["type"] = this.type;
        data["text"] = this.text;
        return data;
    }
}

export interface IApiMessage {
    type?: ApiMessageType;
    text?: string | undefined;
}

export enum ApiMessageType {
    _0 = 0,
    _1 = 1,
    _2 = 2,
    _3 = 3,
}

export class Candidate implements ICandidate {
    id?: string;
    name?: string | undefined;
    skills?: string[] | undefined;
    profileUrl?: string | undefined;
    summary?: string | undefined;
    location?: Location;
    availableFrom?: Date;
    isSpecial?: boolean;

    constructor(data?: ICandidate) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            if (Array.isArray(_data["skills"])) {
                this.skills = [] as any;
                for (let item of _data["skills"])
                    this.skills!.push(item);
            }
            this.profileUrl = _data["profileUrl"];
            this.summary = _data["summary"];
            this.location = _data["location"] ? Location.fromJS(_data["location"]) : <any>undefined;
            this.availableFrom = _data["availableFrom"] ? new Date(_data["availableFrom"].toString()) : <any>undefined;
            this.isSpecial = _data["isSpecial"];
        }
    }

    static fromJS(data: any): Candidate {
        data = typeof data === 'object' ? data : {};
        let result = new Candidate();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        if (Array.isArray(this.skills)) {
            data["skills"] = [];
            for (let item of this.skills)
                data["skills"].push(item);
        }
        data["profileUrl"] = this.profileUrl;
        data["summary"] = this.summary;
        data["location"] = this.location ? this.location.toJSON() : <any>undefined;
        data["availableFrom"] = this.availableFrom ? this.availableFrom.toISOString() : <any>undefined;
        data["isSpecial"] = this.isSpecial;
        return data;
    }
}

export interface ICandidate {
    id?: string;
    name?: string | undefined;
    skills?: string[] | undefined;
    profileUrl?: string | undefined;
    summary?: string | undefined;
    location?: Location;
    availableFrom?: Date;
    isSpecial?: boolean;
}

export class Job implements IJob {
    id?: string;
    website?: string | undefined;
    title?: string | undefined;
    company?: string | undefined;
    location?: Location;
    language?: string | undefined;
    description?: string | undefined;
    salary?: Salary;
    posterName?: string | undefined;
    postedDate?: Date;
    url?: string | undefined;
    tags?: string[] | undefined;

    constructor(data?: IJob) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.website = _data["website"];
            this.title = _data["title"];
            this.company = _data["company"];
            this.location = _data["location"] ? Location.fromJS(_data["location"]) : <any>undefined;
            this.language = _data["language"];
            this.description = _data["description"];
            this.salary = _data["salary"] ? Salary.fromJS(_data["salary"]) : <any>undefined;
            this.posterName = _data["posterName"];
            this.postedDate = _data["postedDate"] ? new Date(_data["postedDate"].toString()) : <any>undefined;
            this.url = _data["url"];
            if (Array.isArray(_data["tags"])) {
                this.tags = [] as any;
                for (let item of _data["tags"])
                    this.tags!.push(item);
            }
        }
    }

    static fromJS(data: any): Job {
        data = typeof data === 'object' ? data : {};
        let result = new Job();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["website"] = this.website;
        data["title"] = this.title;
        data["company"] = this.company;
        data["location"] = this.location ? this.location.toJSON() : <any>undefined;
        data["language"] = this.language;
        data["description"] = this.description;
        data["salary"] = this.salary ? this.salary.toJSON() : <any>undefined;
        data["posterName"] = this.posterName;
        data["postedDate"] = this.postedDate ? this.postedDate.toISOString() : <any>undefined;
        data["url"] = this.url;
        if (Array.isArray(this.tags)) {
            data["tags"] = [];
            for (let item of this.tags)
                data["tags"].push(item);
        }
        return data;
    }
}

export interface IJob {
    id?: string;
    website?: string | undefined;
    title?: string | undefined;
    company?: string | undefined;
    location?: Location;
    language?: string | undefined;
    description?: string | undefined;
    salary?: Salary;
    posterName?: string | undefined;
    postedDate?: Date;
    url?: string | undefined;
    tags?: string[] | undefined;
}

export class JobListResponse implements IJobListResponse {
    isSuccess?: boolean;
    totalCount?: number;
    jobs?: Job[] | undefined;
    messages?: ApiMessage[] | undefined;

    constructor(data?: IJobListResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.isSuccess = _data["isSuccess"];
            this.totalCount = _data["totalCount"];
            if (Array.isArray(_data["jobs"])) {
                this.jobs = [] as any;
                for (let item of _data["jobs"])
                    this.jobs!.push(Job.fromJS(item));
            }
            if (Array.isArray(_data["messages"])) {
                this.messages = [] as any;
                for (let item of _data["messages"])
                    this.messages!.push(ApiMessage.fromJS(item));
            }
        }
    }

    static fromJS(data: any): JobListResponse {
        data = typeof data === 'object' ? data : {};
        let result = new JobListResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["isSuccess"] = this.isSuccess;
        data["totalCount"] = this.totalCount;
        if (Array.isArray(this.jobs)) {
            data["jobs"] = [];
            for (let item of this.jobs)
                data["jobs"].push(item.toJSON());
        }
        if (Array.isArray(this.messages)) {
            data["messages"] = [];
            for (let item of this.messages)
                data["messages"].push(item.toJSON());
        }
        return data;
    }
}

export interface IJobListResponse {
    isSuccess?: boolean;
    totalCount?: number;
    jobs?: Job[] | undefined;
    messages?: ApiMessage[] | undefined;
}

export class KeywordTags implements IKeywordTags {
    roles?: string[] | undefined;
    skills?: string[] | undefined;
    domains?: string[] | undefined;
    employment?: string[] | undefined;
    locations?: string[] | undefined;

    constructor(data?: IKeywordTags) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["roles"])) {
                this.roles = [] as any;
                for (let item of _data["roles"])
                    this.roles!.push(item);
            }
            if (Array.isArray(_data["skills"])) {
                this.skills = [] as any;
                for (let item of _data["skills"])
                    this.skills!.push(item);
            }
            if (Array.isArray(_data["domains"])) {
                this.domains = [] as any;
                for (let item of _data["domains"])
                    this.domains!.push(item);
            }
            if (Array.isArray(_data["employment"])) {
                this.employment = [] as any;
                for (let item of _data["employment"])
                    this.employment!.push(item);
            }
            if (Array.isArray(_data["locations"])) {
                this.locations = [] as any;
                for (let item of _data["locations"])
                    this.locations!.push(item);
            }
        }
    }

    static fromJS(data: any): KeywordTags {
        data = typeof data === 'object' ? data : {};
        let result = new KeywordTags();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.roles)) {
            data["roles"] = [];
            for (let item of this.roles)
                data["roles"].push(item);
        }
        if (Array.isArray(this.skills)) {
            data["skills"] = [];
            for (let item of this.skills)
                data["skills"].push(item);
        }
        if (Array.isArray(this.domains)) {
            data["domains"] = [];
            for (let item of this.domains)
                data["domains"].push(item);
        }
        if (Array.isArray(this.employment)) {
            data["employment"] = [];
            for (let item of this.employment)
                data["employment"].push(item);
        }
        if (Array.isArray(this.locations)) {
            data["locations"] = [];
            for (let item of this.locations)
                data["locations"].push(item);
        }
        return data;
    }
}

export interface IKeywordTags {
    roles?: string[] | undefined;
    skills?: string[] | undefined;
    domains?: string[] | undefined;
    employment?: string[] | undefined;
    locations?: string[] | undefined;
}

export class Location implements ILocation {
    type?: LocationType;
    city?: string | undefined;
    country?: string | undefined;

    constructor(data?: ILocation) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.type = _data["type"];
            this.city = _data["city"];
            this.country = _data["country"];
        }
    }

    static fromJS(data: any): Location {
        data = typeof data === 'object' ? data : {};
        let result = new Location();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["type"] = this.type;
        data["city"] = this.city;
        data["country"] = this.country;
        return data;
    }
}

export interface ILocation {
    type?: LocationType;
    city?: string | undefined;
    country?: string | undefined;
}

export enum LocationType {
    _0 = 0,
    _1 = 1,
    _2 = 2,
}

export class Salary implements ISalary {
    currencyCode?: string | undefined;
    min?: number | undefined;
    max?: number | undefined;
    timeUnit?: SalaryTimeUnit;
    convertedMin?: number | undefined;
    convertedMax?: number | undefined;
    baseCurrencyCode?: string | undefined;
    exchangeRateUpdatedAt?: Date | undefined;

    constructor(data?: ISalary) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.currencyCode = _data["currencyCode"];
            this.min = _data["min"];
            this.max = _data["max"];
            this.timeUnit = _data["timeUnit"];
            this.convertedMin = _data["convertedMin"];
            this.convertedMax = _data["convertedMax"];
            this.baseCurrencyCode = _data["baseCurrencyCode"];
            this.exchangeRateUpdatedAt = _data["exchangeRateUpdatedAt"] ? new Date(_data["exchangeRateUpdatedAt"].toString()) : <any>undefined;
        }
    }

    static fromJS(data: any): Salary {
        data = typeof data === 'object' ? data : {};
        let result = new Salary();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["currencyCode"] = this.currencyCode;
        data["min"] = this.min;
        data["max"] = this.max;
        data["timeUnit"] = this.timeUnit;
        data["convertedMin"] = this.convertedMin;
        data["convertedMax"] = this.convertedMax;
        data["baseCurrencyCode"] = this.baseCurrencyCode;
        data["exchangeRateUpdatedAt"] = this.exchangeRateUpdatedAt ? this.exchangeRateUpdatedAt.toISOString() : <any>undefined;
        return data;
    }
}

export interface ISalary {
    currencyCode?: string | undefined;
    min?: number | undefined;
    max?: number | undefined;
    timeUnit?: SalaryTimeUnit;
    convertedMin?: number | undefined;
    convertedMax?: number | undefined;
    baseCurrencyCode?: string | undefined;
    exchangeRateUpdatedAt?: Date | undefined;
}

export enum SalaryTimeUnit {
    _0 = 0,
    _1 = 1,
    _2 = 2,
    _3 = 3,
    _4 = 4,
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}