name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      VITE_API_KEY: ci_test_key
      API_KEY: ci_test_key

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # - name: Clear NuGet cache
      #   run: dotnet nuget locals all --clear

      - name: Restore .NET dependencies
        run: dotnet restore JobHuntX.API.sln
        working-directory: ${{ github.workspace }}

      - name: Install NSwag CLI
        run: dotnet tool install --global NSwag.ConsoleCore

      - name: Add .dotnet/tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Generate API client (NSwag)
        run: nswag run nswag.ci.json
        working-directory: ${{ github.workspace }}/JobHuntX.API

      - name: Run backend tests
        run: dotnet test JobHuntX.Tests/JobHuntX.Tests.csproj --verbosity normal
        # run: dotnet test JobHuntX.Tests/JobHuntX.Tests.csproj --no-restore --verbosity normal
        working-directory: ${{ github.workspace }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install frontend dependencies
        run: pnpm install
        working-directory: ${{ github.workspace }}/client-app

      - name: Run frontend tests
        run: pnpm test
        working-directory: ${{ github.workspace }}/client-app